---
# Instalação de pacotes iniciais necessários ao ambiente
- hosts: all
  become: true
  tasks:
    - name: Atualizar o índice de pacotes apt
      apt:
        update_cache: yes

    - name: Instalar pacotes necessários para o repositório apt do Kubernetes
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
        state: present
        update_cache: yes

    # Criação do diretório para keyrings, se necessário
    - name: Criar diretório /etc/apt/keyrings se não existir
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    # Baixar a chave GPG do Kubernetes
    - name: Baixar a chave GPG do Kubernetes
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg.raw

    # Converter a chave GPG para o formato adequado
    - name: Converter a chave GPG para o formato adequado
      command: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /etc/apt/keyrings/kubernetes-apt-keyring.gpg.raw

    # Adicionar o repositório do Kubernetes
    - name: Adicionar o repositório do Kubernetes
      ansible.builtin.command: |
        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.23/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list

    # Atualizar pacotes e instalar kubelet, kubeadm e kubectl
    - name: Atualizar o índice de pacotes apt novamente
      apt:
        update_cache: yes

    - name: Instalar kubelet, kubeadm e kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Pin kubelet, kubeadm e kubectl para evitar atualizações automáticas
      command: sudo apt-mark hold kubelet kubeadm kubectl

    # Configuração do ContainerD
    - name: Configura containerd
      blockinfile:
        create: true
        path: /etc/modules-load.d/containerd.conf
        block: |
          overlay
          br_netfilter
  
    - name: Enable kernel modules
      shell: |
        modprobe overlay
        modprobe br_netfilter
  
    - name: Configure IP forwarding and iptables
      blockinfile:
        create: true
        path: /etc/sysctl.conf
        block: |
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
  
    - name: Persist changes
      command: sysctl -p

    - name: Get IP eth1 addr
      shell: ifconfig eth1 | grep 'inet' | cut -d{{':'}} -f2 | awk '{ print $2 }'
      register: output

    - name: Configure Kubelet
      lineinfile:
        path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        line: Evironmet="KUBELET_EXTRA_ARGS=--node-ip={{ output.stdout }}"

    # Iniciando o cluster  
    - name: Initialize the kubernetes cluster using Kubeadm
      command: kubeadm init --apiserver-advertise-address="192.168.50.10" --apiserver-cert-extra-sans="192.168.50.10" --pod-network-cidr=172.16.0.0/16
  
    - name: Create kube directory
      file:
        path: /home/vagrant/.kube
        state: directory
  
    - name: Setup kubeconfig for vagrant user
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant
        group: vagrant
        mode: '0644'

    # Instalação do Calico CNI
    - name: Download calico.conf
      get_url:
        url: https://docs.projectcalico.org/v3.20/manifests/calico.yaml
        dest: /home/vagrant/calico.yaml
  
    - name: Add pod config to calico.yaml
      lineinfile:
        dest: /home/vagrant/calico.yaml
        regexp: '^\s{12}#\s*- name: CALICO_IPV4POOL_CIDR.*$'
        line: '            - name: CALICO_IPV4POOL_CIDR'

    - name: Add pod config to calico.yaml
      lineinfile:
        dest: /home/vagrant/calico.yaml
        regexp: '^\s{12}#\s*  value: "192.168.0.0\/16".*$'
        line: '              value: "172.16.0.0/16"'
  
    - name: Install calico CNI
      become: false
      command: kubectl create -f calico.yaml

    # Gerando kube join
    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      become: false
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
